### ISSUE TITLE
资源包 sf.mcpack 不合法, 加载失败

### ISSUE THREAD

**Issue by fanlepian1** [SofiaRedmond/Slimefun-Geyser#25]
[Geyser-Spigot] The resource pack sf.mcpack has a file in it that meets or exceeds 80 characters in its path (textures/items/jardin_exotico/comida/bbq_double_bacon_wrapped_hot_dog_in_a_tortilla_with_cheese.png, 99 characters long). This will cause problems on some Bedrock platforms. Please rename it to be shorter, or reduce the amount of folders needed to get to the file.
[22:32:17 WARN]: java.lang.IllegalArgumentException: 资源包 sf.mcpack 不合法, 加载失败!
[22:32:17 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.loader.ResourcePackLoader.readPack(ResourcePackLoader.java:160)
[22:32:17 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.loader.ResourcePackLoader.load(ResourcePackLoader.java:102)
[22:32:17 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.loader.ResourcePackLoader.load(ResourcePackLoader.java:57)
[22:32:17 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.DeferredRegistry.lambda$new$2(DeferredRegistry.java:64)
[22:32:17 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.DeferredRegistry.load(DeferredRegistry.java:111)
[22:32:17 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:272)
[22:32:17 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:787)
[22:32:17 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onGeyserEnable(GeyserSpigotPlugin.java:214)
[22:32:17 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.GeyserImpl.reloadGeyser(GeyserImpl.java:673)
[22:32:17 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[22:32:17 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:32:17 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[22:32:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:32:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:32:17 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[22:32:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[22:32:17 WARN]: Caused by: java.lang.IllegalArgumentException: sf.mcpack does not contain a valid pack_manifest.json or manifest.json
[22:32:17 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.loader.ResourcePackLoader.readPack(ResourcePackLoader.java:150)
[22:32:17 WARN]:        ... 15 more

**Comment by zyramystic** [comment]
请使用解压软件解压他 谢谢
Please "unzip" thk
